// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DiaryController from "./diary_controller"
application.register("diary", DiaryController)

import FlashMessageController from "./flash_message_controller"
application.register("flash-message", FlashMessageController)

import HappinessJarController from "./happiness_jar_controller"
application.register("happiness-jar", HappinessJarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PhotoPreviewController from "./photo_preview_controller"
application.register("photo-preview", PhotoPreviewController)

import SceneController from "./scene_controller"
application.register("scene", SceneController)

import StatusSelectorController from "./status_selector_controller"
application.register("status-selector", StatusSelectorController)

import WarmLightController from "./warm_light_controller"
application.register("warm-light", WarmLightController)
