// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DiaryController from "./diary_controller"
application.register("diary", DiaryController)

import FabButtonController from "./fab_button_controller"
application.register("fab-button", FabButtonController)

import FlashMessageController from "./flash_message_controller"
application.register("flash-message", FlashMessageController)

import HappinessJarController from "./happiness_jar_controller"
application.register("happiness-jar", HappinessJarController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import NotificationTimeController from "./notification_time_controller"
application.register("notification-time", NotificationTimeController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import PhotoModalController from "./photo_modal_controller"
application.register("photo-modal", PhotoModalController)

import PhotoPreviewController from "./photo_preview_controller"
application.register("photo-preview", PhotoPreviewController)

import SceneController from "./scene_controller"
application.register("scene", SceneController)

import StatusSelectorController from "./status_selector_controller"
application.register("status-selector", StatusSelectorController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
