FROM ruby:3.3.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
&& curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /etc/apt/keyrings/google-chrome.gpg \
&& echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  yarn \
  vim \
  libvips-dev \
  cron \
  libnss3 libgconf-2-4 libxi6 libxcursor1 libxss1 libxrandr2 libasound2 \
  && rm -rf /var/lib/apt/lists /var/cache/apt/archives


RUN wget https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.0/linux64/chrome-linux64.zip \
  && unzip chrome-linux64.zip \
  && mv chrome-linux64 /usr/local/bin/chrome \
  && ln -s /usr/local/bin/chrome/chrome /usr/bin/google-chrome \
  && rm chrome-linux64.zip


#Chromeのバージョンに合った ChromeDriver を手動でインストール
ARG CHROMEDRIVER_VERSION=141.0.7390.54
RUN curl -fSL -o /tmp/chromedriver.zip \
    "https://storage.googleapis.com/chrome-for-testing-public/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip" \
  && unzip -q /tmp/chromedriver.zip -d /tmp \
  && mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver \
  && chmod +x /usr/bin/chromedriver \
  && rm -rf /tmp/chromedriver.zip /tmp/chromedriver-linux64


RUN mkdir /myapp
WORKDIR /myapp

RUN gem install bundler

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

COPY . /myapp