# このファイルには、アプリ内で使用を禁止する単語をリストします。
# ユーザー名、日記の内容、自己紹介などで使用されます。
# アプリのポジティブな雰囲気を保つために、ネガティブな表現や攻撃的な言葉をブロックします。

blocked_words:
  # --- 攻撃的・暴力的な表現 ---
  - 死ね
  - しね
  - シネ
  - shine
  - 殺す
  - ころす
  - コロス
  - korosu
  - 殴る
  - なぐる
  - 暴力
  - ぼうりょく
  - 虐待
  - ぎゃくたい
  - 消えろ
  - きえろ
  - 氏ね
  - 4ね

  # --- 誹謗中傷・侮辱的な表現 ---
  - バカ
  - ばか
  - baka
  - 馬鹿
  - アホ
  - あほ
  - aho
  - 間抜け
  - まぬけ
  - キモい
  - きもい
  - kimoi
  - きしょい
  - キショイ
  - ウザい
  - うざい
  - uzai
  - ゴミ
  - ごみ
  - gomi
  - クズ
  - くず
  - kuzu
  - カス
  - かす
  - kasu
  - クソ
  - くそ
  - kuso
  - ks
  - 糞
  - ブス
  - ぶす
  - busu
  - デブ
  - でぶ
  - debu
  - ハゲ
  - はげ
  - hage
  - チビ
  - ちび
  - chibi
  - 雑魚
  - ざこ
  - zako
  - 無能
  - むのう
  - munou

  # --- 差別的な表現 ---
  - ガイジ
  - がいじ
  - gaiji
  - キチガイ
  - きちがい
  - kichigai


  # --- 自殺・自傷行為を助長する表現 ---
  - 自殺
  - じさつ
  - jisatsu
  - 死にたい
  - しにたい
  - リスカ
  - りすか
  - リストカット
  - OD
  - od
  - オーバードーズ
  - overdoze

  # --- 性的・わいせつな表現 ---
  - エロ
  - えろ
  - ero
  - セックス
  - せっくす
  - sex
  - s○x
  - 性交
  - わいせつ
  - 淫乱
  - 売春
  - 援助交際
  - 援交
  - パパ活
  - ママ活

  # --- 犯罪を助長する表現 ---
  - 薬物
  - 大麻
  - 覚醒剤
  - 麻薬
  - 違法
  - 脱法